# Generated by Django 5.1.7 on 2025-08-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('chemical_name', models.CharField(blank=True, max_length=255, null=True)),
                ('toxicity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('application_methods', models.TextField(blank=True, null=True)),
                ('safety_precautions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
