# Generated by Django 5.1.7 on 2025-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pesticide'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
