// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3QLbPMdyQPxu3NO47oepx0gt4X5hVYBg',
    appId: '1:599115428194:web:ceb0f403e87968ea00bc3b',
    messagingSenderId: '599115428194',
    projectId: 'frontend-dd37c',
    authDomain: 'frontend-dd37c.firebaseapp.com',
    storageBucket: 'frontend-dd37c.firebasestorage.app',
    measurementId: 'G-5FWJ6KNKP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfXsCtczmXuryjUVIVYP72nUrDgzyDStM',
    appId: '1:599115428194:android:d96223bda060817c00bc3b',
    messagingSenderId: '599115428194',
    projectId: 'frontend-dd37c',
    storageBucket: 'frontend-dd37c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc0jdBJj-yEmaqEJiILaAEjnIhrebDkF0',
    appId: '1:599115428194:ios:829e08a16742361a00bc3b',
    messagingSenderId: '599115428194',
    projectId: 'frontend-dd37c',
    storageBucket: 'frontend-dd37c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc0jdBJj-yEmaqEJiILaAEjnIhrebDkF0',
    appId: '1:599115428194:ios:829e08a16742361a00bc3b',
    messagingSenderId: '599115428194',
    projectId: 'frontend-dd37c',
    storageBucket: 'frontend-dd37c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3QLbPMdyQPxu3NO47oepx0gt4X5hVYBg',
    appId: '1:599115428194:web:37ca1ff10f66020100bc3b',
    messagingSenderId: '599115428194',
    projectId: 'frontend-dd37c',
    authDomain: 'frontend-dd37c.firebaseapp.com',
    storageBucket: 'frontend-dd37c.firebasestorage.app',
    measurementId: 'G-S2NVQHF7FK',
  );

}